version: '3.8'

services:

  auth_service:
    container_name: auth_service
    build: .
    env_file:
      - ./.env
    ports:
      - 8001:8001
    depends_on:
      - auth_service_db
    networks:
      - auth_app_network

  auth_service_db:
    container_name: auth_service_db
    image: postgres:14.4-alpine
    volumes:
      - auth_postgres_data:/var/lib/postgresql/data
    env_file:
      - ./.env_db
    restart: always
    ports:
      - 5433:5433
    networks:
      - auth_app_network

volumes:
  auth_postgres_data:

networks:
  auth_app_network:
