"""empty message

Revision ID: 4a57878e0f3c
Revises: 
Create Date: 2025-02-01 20:55:01.698536

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a57878e0f3c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('name', sa.String(length=30), nullable=False, comment='Username'),
    sa.Column('surname', sa.String(length=30), nullable=False, comment='User surname'),
    sa.Column('login', sa.String(length=30), nullable=False, comment='User login'),
    sa.Column('email', sa.String(length=50), nullable=False, comment='User email'),
    sa.Column('hashed_pwd', sa.Text(), nullable=False, comment='User hashed password'),
    sa.Column('role', sa.Enum('admin', 'user', 'executor', name='userrole'), nullable=False, comment='User role'),
    sa.Column('id', sa.UUID(), nullable=False, comment='UUID identifier'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Creation datetime'),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Update datetime'),
    sa.PrimaryKeyConstraint('id', name=op.f('PK_users')),
    sa.UniqueConstraint('email', name=op.f('UQ_users_email')),
    sa.UniqueConstraint('login', name=op.f('UQ_users_login')),
    schema='authorization_service'
    )
    op.create_table('tokens',
    sa.Column('jti', sa.UUID(), nullable=False, comment='JWT identifier'),
    sa.Column('subject', sa.UUID(), nullable=False, comment='User'),
    sa.Column('user_agent', sa.String(length=100), nullable=False, comment='User device description'),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False, comment='Creation datetime'),
    sa.ForeignKeyConstraint(['subject'], ['authorization_service.users.id'], name=op.f('FK_tokens_subject_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('jti', name=op.f('PK_tokens')),
    schema='authorization_service'
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens', schema='authorization_service')
    op.drop_table('users', schema='authorization_service')
    op.execute("DROP TYPE IF EXISTS userrole;")
    # ### end Alembic commands ###
