name: Check-on-merge
on:
  push:
    branches:
      - main

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Update python
        run: sudo add-apt-repository ppa:deadsnakes/ppa && sudo apt install python3.13
      - name: Install PostgreSQL
        run: sudo apt-get install postgresql postgresql-client
      - name: Run PostgreSQL
        run: sudo service postgresql start
      - name: Setup PostgreSQL
        run: |
          sudo -u postgres psql -c "ALTER USER postgres PASSWORD 'postgres';"
      - name: Install poetry
        run: pip install poetry==1.8.3
      - name: Install deps
        run: poetry install
      - name: Ruff check
        run: |
          poetry run ruff check
          poetry run ruff check --select I
      - name: Run tests
        run: poetry run pytest .
